name: Android Pull Request Quality Check 

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: Android/Nothing

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: copy mock of firebase as real
      uses: canastro/copy-file-action@master
      with:
        source: "app/mock-google-services.json"
        target: "app/google-services.json"

    - name: Setup Android problem matchers
      uses: jonasb/android-problem-matchers-action@v1

    - name: Lint the feature
      run: ./gradlew lintDebug

    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest --stacktrace
